apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-deployment
  labels:
    app: shoppingapi
spec:
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      containers:
        - name: shoppingapi
          image: shoppingacr5487.azurecr.io/shoppingapi:v1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
               path: /api/product
               port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/product
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
      imagePullSecrets:
        - name: shoppingacr54116026becc-auth
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapi
spec:  
  selector:
    app: shoppingapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080